title:  drbarrett
tagline:  another boring blog

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  #disqus_shortname: 'https-lenpaul-github-io-lagrange'

#google-ID: ''

menu:
- {name: 'about', path: 'menu', url: 'about.html'}
- {name: 'archive', path: 'menu', url: 'archive.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/drbarrett'}
- {icon: 'twitter', link: 'https://twitter.com/aqua_dan'}
- {icon: 'envelope', link: 'mailto:drbarrett@cmu.edu'}
- {icon: 'rss-square', link: '/feed.xml'}
